blank_issues_enabled: false
contact_links:
    - name: Ask a Question ğŸ’¡
      url: https://github.com/composer-unused/composer-unused/discussions/new?category=q-a
      about: Ask the community for help
    - name: Feature Request â“
      url: https://github.com/composer-unused/composer-unused/discussions/new?category=ideas
      about: Share ideas for new features
